### PR TITLE
Add SDE Sampler

### PR DESCRIPTION
**Pull request by ResidentChief**
Allows the horde to use the DPM++ SDE Sampler

### CODE REVIEW

**Comment by db0** [comment]
This is tested, ye?

**Comment by ResidentChief** [comment]
Yeah had it going on my worker (swapped dpm_fast as the trigger) and it
works well

**Comment by db0** [comment]
Is it done? It's still in draft

**Comment by ResidentChief** [comment]
Well it worked when i told requests marked as dpm_fast to use the dpmpp_sde
sampler, but would like to test with proper request inputs from the horde

**Pull request merged**
