### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by Arborym**

### CODE REVIEW

**Comment by tazlin** [comment]
Many of the changes appear to be the result of automatically applied linting rules, or is close enough to it that at least one linter and/or rule set would probably enforce something close to this. I do see though that at least some manual changes were made.

My two cents is that if this is going to be merged, @Arborym should specify which linter and rules are being applied here, if any, and it should be included in `style.py`. If no specific extra linter was used this specific time, there are in fact rulesets that would be applicable. 

Also +1 from me on adding some type hints - they only improve readability and maintainability.

**Comment by jug-dev** [comment]
I agree with @tazlin. 

It's clearly up to @db0 to decide what style he wants, I just echo what @tazlin stated in that it would be good to get those rules in the CI style check rather than do occasional large refactoring.

**Comment by db0** [comment]
I agree. @Arborym you need to let us know when you're planning to do massive reformatting like this

To start, can you adjust the style.py so that it can enforce perform the same style?

**Comment by Arborym** [comment]
I added the linting I used to `style.py` and `pyproject.toml`. There are a lot of things for Ruff, so some of them could be removed, depending on your interests. The rest of the changes I made were manual.

**Comment by db0** [comment]
The choice of all three was suggested in a PR. If we can do with 2 and have all the same rules I'm ok with it

**Comment by db0** [comment]
Feel free to send the PR :D

**Comment by Arborym** [comment]
Transitioning Ruff rules to #149, will create a new PR with my manual refactorings after that is resolved.

**Pull request closed without merging**
