### PR TITLE
Reload model database if we find an unknown model

### LINKED ISSUE #45: If new models are added to the database the worker errors
```
Model name requested Abyss OrangeMix in bridgeData is unknown to us. Please check your configuration. Aborting!
Model name requested Anything v3 in bridgeData is unknown to us. Please check your configuration. Aborting!
Model name requested Woop-Woop Photo in bridgeData is unknown to us. Please check your configuration. Aborting!
```

The worker doesn't seem to reload the remote model database.

### PR DESCRIPTION
**Pull request by jug-dev**
Closes #45

### CODE REVIEW

**Comment by db0** [comment]
Can you add a check so that it doesn't pull every time in case the user makes a typo? Make it max download the model list max 1 per minute.

**Comment by jug-dev** [comment]
Will do.

**Comment by jug-dev** [comment]
Doesn't rapidly download the model database (max once per 60 seconds) and if database refresh it's fix the missing model, never download the database again looking for that particular model.

**Comment by db0** [comment]
This is tested on your end?

**Comment by jug-dev** [comment]
Yes. I have been running this locally. Behaves as expected when encountering an unknown model. Tries to download once, then reverts to current behavior.
```
INFO       | 2023-02-12 20:42:00.766170 | worker.bridge_data.framework:check_models:132 - Downloading model database trying to find model Foo
INIT       | Downloading | Model Reference
INIT       | OK          | Model Reference
WARNING    | 2023-02-12 20:42:01.089950 | worker.bridge_data.framework:check_models:142 - Model name requested Foo in bridgeData is unknown to us. Please check your configuration. Aborting!
```

**Pull request merged**
