### PR TITLE
Ruff migrate

### PR DESCRIPTION
**Pull request by tazlin**
@db0 @jug-dev @Arborym 

3/31/23 
The breakdown as of [18f370d](https://github.com/db0/AI-Horde-Worker/pull/149/commits/18f370dfffa42c1e834d4465f6838e4bc5557ac5) is as follows:

- flake8 and isort removed from style.py
- ruff is first in the run order, then black
- Added a couple print statements for debug information in style.py (use `--debug`)
- If a folder called 'nataili' exists in your working directory, style.py will quit immediately and prompt you to remove it.
- Upgrades workflows\lint.yml to use the latest github action versions.

All available rules for ruff can be found at https://beta.ruff.rs/docs/rules/. 
The state of rules enforced, as of writing, in this PR (see `project.toml`) is:
```python
select = [
    "A",    # flake8-builtins
    "I",    # isort 
    # "S",    # Bandit
    "F",    # pyflakes
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings

    "YTT",  # flake8-2020
    # "BLE",    # flake8-blind-except
    # "B",    # flake8-bugbear
    "COM",  # flake8-commas
    "C4",   # flake8-comprehensions
    # "G",    # flake8-logging-format
    "INP",  # flake8-no-pep420
    "PIE",  # flake8-pie
    # "T20",  # flake8-print
    # "UP",   # pyupgrade
    "RSE",  # flake8-raise 
    "RET",  # flake8-return
    # "SLF",  # flake8-self
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    # "TRY",  # tryceratops 
    "RUF100"
]
ignore = [
    "A002", # Argument `x` is shadowing a python builtin
    "A003", # Class attribute `x` is shadowing a python builtin
]
```

The ones enabled currently as of this PR include those which are roughly in line with what was would have changed in #142. Further, while in #142 `select` was set to `ALL`, this PR spells out the specific linting rules I would personally suggest. A few manual refactorings by @Arborym in #142 are not included, nor are any type hints (yet).

Of the ones suggested, but not yet included, I would put particular emphasis on **bandit** (which can spot security issues), **flake8-blind-except** (which is judiciously violated in this project via the idiom `except Exception:`) and **tryceratops** (which would enforce `logger.exception` over `logger.error`).

If anyone has any strong feelings about anything at this stage, let me know, otherwise, I will include the commented out rules and do the needful to enforce them.

### CODE REVIEW

**Comment by Arborym** [comment]
@tazlin Would it make sense for me to close my PR and just include my manual refactorings in a new one?

**Comment by tazlin** [comment]
@Arborym I noted you as a co-author, and left out your manual changes in the spirit of allowing you to do so, if you so desired. If you'd like, either you can make a commit after this PR get's sorted out, or I can do do the merge resolution with your fork if you'd rather not. If you decide on the later, just leave your branch up and I'll get to it when this is in.

**Comment by db0** [comment]
I assume you've tested this?

**Comment by tazlin** [comment]
‘style.py’ will have been run for each commit and certain code changes are still working, but I haven’t done an exhaustive test. I have marked this PR as a draft for that reason.

The CI is failing because isort as configured live would not agree with the results of the PR’s ‘style.py’.

**Comment by db0** [comment]
OK, I'll try to download and run it on my end. There's a few logical changes which seems like they're OK but who knows.

**Comment by db0** [comment]
Renaming it actually the better approach here as it conflicts with the nataili library. It's just a pita because well need to move all the models for the user

**Comment by tazlin** [comment]
> Renaming it actually the better approach here as it conflicts with the nataili library. It's just a pita because well need to move all the models for the user

I do agree - either the project has to move to a `src/` type structure, or `nataili/` as to move.

**Comment by db0** [comment]
So the CI  is succeeding currently. Can we merge this despite #151 not being done yet?

**Comment by tazlin** [comment]
> So the CI is succeeding currently. Can we merge this despite #151 not being done yet?

All commits after you began testing are to the build/CI pipline or are automatically applied lint/format rules. 

I feel reasonably confident things are ok to merge.

**Comment by tazlin** [comment]
Just note that any dev wanting to push a commit is going to locally have `style.py` refuse to run if `nataili/` is there.

**Comment by db0** [comment]
OK fixed.

**Pull request merged**
