### PR TITLE
Add scribe docker container. Move all docker builds and scripts under /docker

### PR DESCRIPTION
**Pull request by guspuffygit**
###### Purpose
* Create a scribe docker container
* Rename default docker container to end in -stable-diffusion
* Scribe container ends in -scribe
* Add README.md updates for environment variables

###### Testing
* Built both containers using github actions, tested scribe locally

### CODE REVIEW

**Comment by db0** [comment]
> Rename default docker container to end in -stable-diffusion

Can you make it end in `-dreamer` instead?

**Comment by wesmcouch** [comment]
Yeah I'll modify tm morning

**Comment by guspuffygit** [comment]
Yeah I'll modify

**Comment by db0** [comment]
shit, I didn't know this would close this. Can you reopen against the main branch?

**Comment by guspuffygit** [comment]
yeah no worries, I was messing with it today and there are still a few issues getting the dreamer container synced to the new config changes, once I get those worked out I will reopen

**Pull request closed without merging**
