### PR TITLE
Add prompt weight support in the format of (subprompt:1.1)

### PR DESCRIPTION
**Pull request by tijszwinkels**
For example:
A photograph of an (astronaut:1.2) riding a horse on the moon

I've been looking for a good code example to add prompt weights, but most implementations I found just split the prompt in subprompts, and make a weighted average of the embeddings of these subprompts. This has two disadvantages:

- Even adding a small weight tweak to one of the words changes the image completely
- Since the prompt is split, information about the context between words is lost. (which is exactly what transformers are good at)

This implementation takes a different approach; It calculates the difference between the whole prompt with and without the weighted subprompt. It takes this difference to be the contribution of the subprompt to the embedding vector, and uses this to subtly modify the original embedding vector on the weight. Results seem much more stable (small tweaks don't disturb the entire result), and I believe this to be a better method.

I'm pretty new to this, so:
- Please test
- Feedback welcome!

### CODE REVIEW

**Comment by tijszwinkels** [comment]
If the 'Pillars of Creation' worker is up, it's running this code. (so the change can easily be tested)

**Comment by tijszwinkels** [comment]
I'm building black (which on Os X rebuilds python. Yikes.) - I'll submit a properly linted version tomorrow morning.

**Comment by tijszwinkels** [comment]
Last lint error is not in a file I touched.

**Comment by db0** [comment]
Thanks mate. Give us a bit of time to test this

**Comment by tijszwinkels** [comment]
heads-up; Just did a rebase (so I could fix the last linter error)

**Comment by tijszwinkels** [comment]
I might take 'Pillars of Creation' down for a bit, but 'Pillars of Creation going Brrr' is running the same branch, and should be up for at least as long as the former is down.

**Comment by db0** [comment]
Can you rebase please? had to catch one more exception

**Comment by tijszwinkels** [comment]
rebase + make linter happy for that last fix. :)

**Pull request merged**
