### PR TITLE
Add HiRes-Fix functionality

### PR DESCRIPTION
**Pull request by ResidentChief**
This adds the ability for an image to be generated, blown up to a higher resolution then img2img applied to the image.

There is a PR on the AI-Horde for the generation parameter - there will also need to be a change to the kudos calculation as the second run takes a lot of resource given the higher resolution involved, and a change to the job "allocator" to say not to send hires_fix jobs to workers that have allow_img2img = False.

### CODE REVIEW

**Comment by db0** [comment]
The allow img2img = false it to avoid the risk of getting external images downloaded locally. It doesn't make sense to use that as a prevention. 

As for the power, the current implementation basically uses the requested resolution as the final resolution right? So the worker should be able to img2img in that requested resolution if they were able to text2gen into it as well. If anything, the kudos calculation should be lowered when using hires_fix, since text2img at the higher res is less expensive at img2img at low denoise.

**Comment by db0** [comment]
Had you tested this? I had to fix it. The hires_fix was even under the wrong place (you had it under img2img which it would never go, so it was never used, just generated 512x512)

I also, can't see the point of it in the current implementation. Currently all it does it add the extra 512x512 gen and then generates almost the same steps at the higher resolution, so you don't gain anything over just generating the higher resolution in the first place. What am I missing?

**Comment by db0** [comment]
I am also not getting the same image in the higher resolution. The "upscaled" image is completely different from the image at 512x512 for me

**Comment by db0** [comment]
I don't feel this implementation is correct, but I don't understand clearly what this is achieving either.

same seed

* 512x512: image
* 768x768: image
* 768x768x hires: image

So it just kinda looks like the 768x768 which makes sense as you're img2img the 512x512 at high denoising strength. I just don't get it

**Comment by db0** [comment]
So reading what they're trying to achieve in a1111, the hires_fix should be keeping the 512x512 composition, and stay relatively fast.

image

The current implementation is not doing that.

**Comment by db0** [comment]
Tried to update this PR so that it uses a lower denoising strength during img2img but it just ends up blurry. I can't figure out myself how this is supposed to work according to the stated goals. Please take a look.

**Comment by db0** [comment]
@ResidentChief I understand this is already merged into nataili 0.2.0?

**Comment by ResidentChief** [comment]
Hlky said they were going to do it, clip skip went direct to 0.2

**Comment by hlky** [comment]
[Ported to Nataili](https://github.com/Sygil-Dev/nataili/commit/8b3fa18f20a2f633cab80b7b5aa084f47e88f6eb)

**Comment by db0** [comment]
closing since this is on nataili side now

**Pull request closed without merging**
